# Default values for yb-iot-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "yugabytedb/yb-iot"
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 8080

kafkaHostPort: localhost:9002
zookeeperHostPort: localhost:2181
yugabyteDBHost: localhost
yugabyteDBYCQLPort: 9042

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
